### ISSUE TITLE
issues with simple example 

### ISSUE THREAD

**Issue by nissandjac** [pbs-assess/sdmTMB#106]
I am having issues running the examples for the package. 

```

library(tidyverse)
library(sdmTMB)

mesh <- make_mesh(pcod, xy_cols = c("X", "Y"), cutoff = 10)

fit <- sdmTMB(
  density ~ s(depth),
  data = pcod,
  family = tweedie(link = "log"),
  mesh = mesh,
  spatial = "on"
)

```
Then I get the error

Error in .Call("getParameterOrder", data, parameters, reportenv, control,  : 
  Incorrect number of arguments (4), expecting 3 for 'getParameterOrder'
In addition: Warning:
I checkDepPackageVersion(dep_pkg = "TMB") :
  Package version inconsistency detected.
glmmTMB was built with TMB version 1.8.1
Current TMB version is 1.9.0
Please re-install glmmTMB from source or restore original ‘TMB’ package (see '?reinstalling' for more information)

Is this a version issue or am I missing something?

**Comment by ericward-noaa** [comment]
Hey Nis -- it's not a version issue, because I have the same glmmTMB / TMB versions, but can get the example to run. IF you do sessionInfo(), what OS / version of R are you on?

**Comment by nissandjac** [comment]
Hi Eric, 

R version 4.0.1 (2020-06-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Not the newest R version not the oldest. 

I tried reinstalling sdmTMB without dependencies (I had reinstalled glmmTMB and TMB several times), and it seems to have solved the issue. Perhaps a file was corrupted, sorry for the inconvenience.

**Comment by nissandjac** [comment]
That actually makes sense. 

Thanks for the answer, I'm sure that will be useful in other applications as well
