### ISSUE TITLE
predict with nsim > 0 fails with multiple spatially varying terms

### ISSUE THREAD

**Issue by Ax3man** [pbs-assess/sdmTMB#107]
Hi, thanks for a really neat package, works great on really large datasets!

I'm trying to predict the spatially varying slopes of a model which has multiple terms in the `spatial_varying` formula. This works for a normal prediction, but not when simulating.

Here's a reproducible example, from slightly altering your vignette.

```
library(dplyr)
library(sdmTMB)

d <- filter(pcod, year == 2003)

pcod_spde <- make_mesh(d, c("X", "Y"), cutoff = 12)
plot(pcod_spde)

m1 <- sdmTMB(
  density ~ 1, data = d,
  mesh = pcod_spde, family = tweedie(link = "log"),
  spatial_varying = ~ 0 + depth_mean, 
)
p1a <- predict(m1)
p1b <- predict(m1, nsim = 10, sims_var = 'zeta_s')
# works great

m2 <- sdmTMB(
  density ~ 1, data = d,
  mesh = pcod_spde, family = tweedie(link = "log"),
  spatial_varying = ~ 0 + depth_mean + depth_sd, 
)
p2a <- predict(m2)
# works great
p2b <- predict(m2, nsim = 10, sims_var = 'zeta_s')
# Error in dimnames(x) <- dn : 
#   length of 'dimnames' [1] not equal to array extent
```

Error is generated [here](https://github.com/pbs-assess/sdmTMB/blob/d04e6b16b873401a8a8f1f85d272ad2ee5ca04b7/R/predict.R#L547), it seems `out` has too many rows. I think instead of having `nrow(newdata)` rows, it appears to be something like `nrow(newdata)` times the number of spatially varying terms.

**Comment by seananderson** [comment]
Thanks for the helpful bug report! You're right. There were also issues with `sims_var` for delta models. It should be fixed [here](https://github.com/pbs-assess/sdmTMB/commit/dd8913d44481b4f3036f050a92f2958d80dbd83d) along with a bunch of tests.

For multiple spatially varying coefficients, they are now returned in a list with each element of the list corresponding to a spatially varying coefficient.

Note that you can also return the entire MVN simulated TMB report list:
``` r
library(sdmTMB)
d <- subset(pcod, year == 2003)
pcod_spde <- make_mesh(d, c("X", "Y"), cutoff = 12)
m1 <- sdmTMB(
    density ~ 1, data = d,
    mesh = pcod_spde, family = tweedie(link = "log"),
    spatial_varying = ~ 0 + depth_mean,
  )
p1b <- predict(m1, nsim = 10, return_tmb_report = TRUE)
  
length(p1b)
#> [1] 10
names(p1b[[1]])
#>  [1] "b_smooth"              "log_range"             "eta_smooth_i"         
#>  [4] "sigma_Z"               "omega_s_A"             "proj_fe"              
#>  [7] "b_rw_t"                "proj_rw_i"             "eta_i"                
#> [10] "proj_epsilon_st_A_vec" "proj_iid_re_i"         "phi"                  
#> [13] "eta_rw_i"              "epsilon_st_A_vec"      "sigma_E"              
#> [16] "ln_smooth_sigma"       "eta_fixed_i"           "eta_iid_re_i"         
#> [19] "proj_rf"               "rho"                   "zeta_s_A"             
#> [22] "proj_omega_s_A"        "sigma_O"               "range"                
#> [25] "proj_eta"              "proj_zeta_s_A"
```

but then it's up to you to parse the list/array/matrix output based on the TMB object names, which isn't a fun exercise.

**Comment by Ax3man** [comment]
Fantastic! Thanks so much for the rapid solution.

So, `p2b` now returns a structure like:
```
List of 2
 $ : num [1:232, 1:10] 20.36 17.97 17.65 4.01 -9.93 ...
 $ : num [1:232, 1:10] -231.2 -204.1 -200.5 -43.5 111.3 ...
```
Could this list be named with the coefficients? So presumably like `setNames(p2b, m2$spatial_varying)`?
