### ISSUE TITLE
wrong error message from get_cog()

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [pbs-assess/sdmTMB#13]
If you run get_cog() on a prediction object created with return_tmb_object = FALSE, it produces the wrong error message (unless something changed very recently that I missed?):

Error: It looks like the model was built with an older version of sdmTMB. Please update the model with `your_model <- sdmTMB:::update_model(your_model)` first before running this function.

**Comment by seananderson** [comment]
That error looks right. It’s because the model now has a few more data inputs like likelihood weights. Do what the message says and it should fix things so that everything works with an older model. You may want to save that new version to avoid having to update it each time.

**Comment by Lewis-Barnett-NOAA** [comment]
Well, I have gotten other errors related to those missing inputs in the past, but I think this is different.  The model was recently fit and running update_model() makes no difference in this case because it has to do with the structure of the output from predict() (whether or not this includes the TMB object as a list), right?  Sorry, I should have dived in and changed the error myself, but needed a sanity check first.  An example:

d <- pcod

pcod_spde <- make_spde(d$X, d$Y, n_knots = 50) # just 50 for example speed
m <- sdmTMB(
 data = d, formula = density ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
 time = "year", spde = pcod_spde, family = tweedie(link = "log")
)

p1 <- predict(m, return_tmb_object = TRUE)
p2 <- predict(m)

get_cog(p1)
get_cog(p2)

**Comment by seananderson** [comment]
Ah, misread your comment. Fixed now.
