### ISSUE TITLE
class of `delta_*()` families is `"list"` not `"family"`

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [pbs-assess/sdmTMB#153]
https://github.com/pbs-assess/sdmTMB/blob/9449eed639cefcef757c4d69f6f239830aae308a/R/families.R#L256-L258

The above line of code and other lines that return a list() for a family leads to
```
class(sdmTMB::delta_gamma())
[1] "list"
```
rather than
```
class(sdmTMB::tweedie()
[1] "family"
class(gaussian())
[1] "family"
```
This is not a big deal, it would just make my downstream code easier when I check to make sure that users are passing an actual family in an input argument rather than some text string or multiple distributions.
THANKS!

**Comment by seananderson** [comment]
Should be done now for all delta families:

``` r
library(sdmTMB)
inherits(delta_gamma(), "family")
#> [1] TRUE
```

<sup>Created on 2023-01-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
