### ISSUE TITLE
Fix 'Additional issues' CRAN checks

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#158]
Deadline January 25

https://cran.r-project.org/web/checks/check_results_sdmTMB.html

- [x] clang-ASAN
- [x] gcc-ASAN
- [x] valgrind

Eric and I think the memory ones are related to `share_range` sometimes being length 1 and sometimes length 2.

Check Details

Version: 0.2.1
- [x] Check: installed package size
Result: NOTE
     installed size is 8.9Mb
     sub-directories of 1Mb or more:
     data 1.7Mb
     libs 5.3Mb
Flavors: r-devel-linux-x86_64-fedora-clang, r-devel-windows-x86_64, r-oldrel-windows-ix86+x86_64

Eric suggests making most vignettes pkgdown web only.

Version: 0.2.1
- [x] Check: Rd cross-references
Result: NOTE
    Undeclared packages ‘future’, ‘lme4’ in Rd xrefs
Flavor: r-devel-linux-x86_64-fedora-clang

Add to suggests!?

Version: 0.2.1
- [x] Check: data for non-ASCII characters
Result: NOTE
     Note: found 2 marked Latin-1 strings
Flavors: r-devel-linux-x86_64-fedora-clang, r-devel-linux-x86_64-fedora-gcc

This may be fun to find.

These ones are impossible to fix, I think:

Version: 0.2.1
Check: package dependencies
Result: NOTE
    Package suggested but not available for checking: 'INLA'
Flavor: r-devel-windows-x86_64

Version: 0.2.1
Check: Rd cross-references
Result: NOTE
    Package unavailable to check Rd xrefs: 'INLA'
Flavor: r-devel-windows-x86_64

**Comment by ericward-noaa** [comment]
The non-ASCII characters are in bc_coast$name_es and bc_coast$name_pt (Canadá)

tools::showNonASCII(bc_coast$name_es)
tools::showNonASCII(bc_coast$name_pt)

**Comment by ericward-noaa** [comment]
Moving notes over here, but if we did want to make most vignettes web only, the mkin package provides a good template

https://github.com/jranke/mkin/blob/main/_pkgdown.yml

**Comment by seananderson** [comment]
Thanks. I've just pushed something to see if it works (and merged cran into main to test). I'm keeping the model description and linking to the rest at the top:
![image](https://user-images.githubusercontent.com/19349/211916254-110e51de-4bc4-415d-94bf-4c315ccf3a52.png)

From looking elsewhere, I think we'll still get a NOTE because of the lib folder size, but not much we can do about that and it shouldn't be a problem.

**Comment by seananderson** [comment]
Actually, I just realized the vignettes probably aren't causing problems on CRAN. They don't have any images because R code isn't executed (no INLA) meaning that they are probably tiny.
