### ISSUE TITLE
sdmTMB_cv: object not found w/ offset

### ISSUE THREAD

**Issue by CamFreshwater** [pbs-assess/sdmTMB#165]
I have been trying to use cross validation to assess model performance but keep running into "object not found" errors. After simplifying the models it seems to be related to the `offset` argument. 

The version with no offset runs:
```
fit_cv <- sdmTMB_cv(
  n_juv ~ 1,
  data = dd,
  mesh = mesh,
  family = sdmTMB::nbinom2(),
  spatial = "on",
  k_folds = 5
)
```

And the version with an offset and without cross validation runs:
```
fit_off <- sdmTMB(
  n_juv ~ 1,
  data = dd,
  offset = log(dd$volume_m3),
  mesh = mesh,
  family = sdmTMB::nbinom2(),
  spatial = "on"
)
```

But sdmTMB_cv with the offset argument does not:
```
fit_cv_off <- sdmTMB_cv(
  n_juv ~ 1,
  data = dd,
  mesh = mesh,
  offset = log(dd$volume_m3),
  family = sdmTMB::nbinom2(),
  spatial = "on",
  k_folds = 5
)
```

This could be a data-specific issue because I don't run into problems using the lingcod example data, but I don't see anything obvious there. Occurs on both Mac and PC with the most recent version of sdmTMB. Apologies in advance if this is something silly and obvious... 

Data and full code available [here](https://github.com/pbs-assess/juvenile-salmon-index/blob/master/R/st_structure_cv.R#L26-L53).

**Comment by CamFreshwater** [comment]
And of course soon as I post, I can't reproduce. Closing for now unless it goes sideways again and I can get a stable reproducible example.

**Comment by seananderson** [comment]
I think the error happens when using the future package:

``` r
  library(sdmTMB)
  library(future)
  plan(multisession)

  d <- pcod_2011
  set.seed(1)
  d$log_effort <- rnorm(nrow(d))

  fit_cv_off <- sdmTMB_cv(
    density ~ 1,
    data = d,
    mesh = pcod_mesh_2011,
    family = tweedie(),
    spatial = "off",
    offset = d$log_effort,
    k_folds = 2
  )
#> Running fits with `future.apply()`.
#> Set a parallel `future::plan()` to use parallel processing.
#> Error in (function (formula, data, mesh, time = NULL, family = gaussian(link = "identity"), : object 'd' not found
```

<sup>Created on 2023-01-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by seananderson** [comment]
OK, should be fixed. At first I made it work with a numeric vector offset, but this seemed fragile depending on the environment the function was called in (e.g., sdmTMB called within the testthat environment). So, `sdmTMB()` now allows a character value for `offset` representing the column name and this seems like a more robust approach with 'future' parallel cross validation. If you try to pass a vector to offset with parallel cross validation it tells you to use the character approach.

**Comment by CamFreshwater** [comment]
Excellent, thanks for pinpointing and addressing that Sean!
