### ISSUE TITLE
Fix mixture scaling for mixture families

### ISSUE THREAD

**Issue by ericward-noaa** [pbs-assess/sdmTMB#225]
@seananderson -- not sure if you had other ways of thinking about this, but I made a change over on the `mix-predict` branch.  

Here's a reproducible example showing more similar results to Kelli / Ian's example:

```
pcod_spde <- make_mesh(pcod, c("X", "Y"), n_knots = 60, type = "kmeans")
m <- sdmTMB(
  data = pcod,
  formula = density ~ 0 + as.factor(year),
  time = "year", mesh = pcod_spde, family = tweedie(link = "log")
)

nd <- replicate_df(qcs_grid, "year", unique(pcod$year))
predictions <- predict(m, newdata = nd, return_tmb_object = TRUE)
ind1 <- get_index(predictions)

m <- sdmTMB(
  data = pcod,
  formula = density ~ 0 + as.factor(year),
  time = "year", mesh = pcod_spde, family = delta_lognormal_mix()
)
predictions <- predict(m, newdata = nd, return_tmb_object = TRUE)
ind2 <- get_index(predictions)

ggplot(ind1, aes(year, est)) + 
  geom_point(col="blue") + 
  geom_point(data=ind2, aes(year, est), col="red")
```

**Comment by seananderson** [comment]
Thanks. I was going to condense the C++ case switches and pull out common
parts in the observation likelihood part. Otherwise, this seems good. I’m
not sure the residuals are correct right now. Can we just take the combined
mean? Wouldn’t we expect that it could be bimodal? We could simulation test
to check. Simulation style (dharma) residuals would be simple.

**Comment by ericward-noaa** [comment]
Thanks, I wasn't sure about best way to reduce the switches, but that'd be great. 

I agree the residuals will be problematic -- if the data are at all multimodal (because of the mixture) and we use the combined mean, residuals should be multimodal. If we were calculating the probability of group assignment for each data point, then I think each point could have its own mean (and residuals would be well behaved) -- I think perhaps putting a warning in residuals() for models that get passed in with these families would be ok for now?

**Comment by kellijohnson-NOAA** [comment]
Sorry my tardiness on this issue, I am looking for the mix-predict branch and I don't see it.

**Comment by seananderson** [comment]
I think this is now fixed in the main branch. Residuals are not fixed, and I think will just error out right now (although DHARMa ones should be fine... or at least as fine as DHARMa residuals are for these types of models).

**Comment by seananderson** [comment]
For future reference, it's fixed mostly in [this commit](https://github.com/pbs-assess/sdmTMB/commit/472db4abca5855423e64f09766db11458d6bcbbe). This still isn't widely tested, so be extra critical of the results and let us know if something looks funny.

**Comment by kellijohnson-NOAA** [comment]
Will do, thanks @seananderson and @ericward-noaa!
