### ISSUE TITLE
Does an extra_time argument still exist?

### ISSUE THREAD

**Issue by ecophilina** [pbs-assess/sdmTMB#227]
Or does this message need updating?
https://github.com/pbs-assess/sdmTMB/blob/main/R/predict.R#LL357C63-L357C63

**Comment by seananderson** [comment]
This was a typo; should have referred to the fitting function argument. [Fixed](https://github.com/pbs-assess/sdmTMB/commit/5752af116dafaecc73c74b3f1159dda4cafb1773).
