### ISSUE TITLE
Add coef() and vcov()

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#241]
Also do check for other common methods that may be missing.

**Comment by ericward-noaa** [comment]
fixef() and ranef() would be other good ones. With ranef() we'd need to decide what to include. The tidy function splits out "ran_pars" and "ran_vals" -- perhaps both? glmmTMB also has sigma() -- which could be included or not, also referenced here: https://github.com/pbs-assess/sdmTMB/issues/72

**Comment by seananderson** [comment]
coef() + vcov() are done now

fixef() and ranef() were already done (I think you did ranef()! )

sigma() has it's own issue, so I'm closing this
