### ISSUE TITLE
Interactions with get_index

### ISSUE THREAD

**Issue by MikkoVihtakari** [pbs-assess/sdmTMB#255]
I am trying to make a model where sex of fish is represented using an interaction allowing sexes to have different trends over time: `sdmTMB(value ~ 0 + fyear * sex + poly(log(depth), 2), ...)`

I can do `ggeffects::ggeffect(fit, terms = c("fyear", "sex"))` to get the marginal effects, but is there a way to split indices to sexes using the `get_index()` function? When I run the function, I get the index with both sexes I presume. At least it is not split by the interaction.

My prediction grid has both sexes `replicate_df`'d.

**Comment by MikkoVihtakari** [comment]
Ah, I see now when I subset one of the sexes from the projection grid, I get index for that sex and when I won't subset, I get the summed-up index. Brilliant! Thanks a lot for help Eric. This issue can be closed from my part.

**Comment by ericward-noaa** [comment]
Ok great - glad it worked!
