### ISSUE TITLE
Send to CRAN

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#26]
Check what other TMB packages are doing to keep size down (e.g. MSEtool vs. glmmTMB). Technically I think it's good to go as is, but we might want to shorten some example and vignette runs and check on Rhub.

**The INLA problem could be insurmountable. See what other packages are doing.**

**Comment by seananderson** [comment]
See https://github.com/fbachl/inlabru for an INLA CRAN example.

Leave in 'additional repositories'. Looks like you need make sure not to run any INLA code on CRAN servers. E.g.:
https://github.com/fbachl/inlabru/blob/d9ed5eca602250b2485d79cfc61e4376a3be5032/R/sampling.R#L59-L70

**Comment by quang-huynh** [comment]
CRAN has generally not given me any flack for large executables

**Comment by seananderson** [comment]
Closing given the more useful 'release' issue https://github.com/pbs-assess/sdmTMB/issues/71
