### ISSUE TITLE
Non-stationary in spatial parameters (variance, decay, etc)

### ISSUE THREAD

**Issue by ericward-noaa** [pbs-assess/sdmTMB#27]
Either summarize anomalies in residuals from predictions in a sdmTMB model (this can be done post-hoc outside of estimation), or internally within TMB with hard restrictions on model parameters by year. Example: AR(1) process, linear or exponential fits, etc

**Comment by seananderson** [comment]
Eric has added this as `epsilon_predictor` in sdmTMB().
