### ISSUE TITLE
`predict()` for a model with spatially varying coefficients requires `newdata`

### ISSUE THREAD

**Issue by ecophilina** [pbs-assess/sdmTMB#279]
Not obvious why this is the case. 
Would be nice if it would use the model data like all other cases.

**Comment by seananderson** [comment]
This part: https://github.com/pbs-assess/sdmTMB/blob/48b391434e9b214c97a3c24cf4f6f7548cac0272/R/predict.R#L838-L840
which is parsing the results from the TMB report, needs to be finished. It needs to match something like this, which is for `newdata`:
https://github.com/pbs-assess/sdmTMB/blob/48b391434e9b214c97a3c24cf4f6f7548cac0272/R/predict.R#L691-L694

**Comment by klwilson23** [comment]
I'm also getting this error as well when calling the `dharma_residuals()` function in `sdmTMBextra`

```
s_spp_re <- simulate(fit_spp_re, nsim = 500)
r_spp_re <- sdmTMBextra::dharma_residuals(s_spp_re, fit_spp_re, plot = FALSE)
Error in `predict()`:
! Prediction with `newdata = NULL` is not supported with spatially varying coefficients yet.
Please provide your data to `newdata`.
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by seananderson** [comment]
OK, fixed now. All I had to do was uncomment that code. I wish I could remember why I disabled it at some point, but everything looks fine to me in tests.
