### ISSUE TITLE
Issue with data in predict() 

### ISSUE THREAD

**Issue by ericward-noaa** [pbs-assess/sdmTMB#28]
There's a type mismatch error that gets thrown with predict() when one of two things occurs:

- Dataframe included in the call to sdmTMB() contains a covariate that has been centered or scaled with scale() , prediction dataframe includes the same variable on a different scale (e.g. scale() not called)
- Dataframe into sdmTMB includes raw variables, but the dataframe input into predict() includes one that has been centered or scaled with scale() 

The reason this is occurring is that scale() returns a column matrix, and that type is maintained in the dataframe. Several ways to fix this, but perhaps just put a as.data.frame() call in predict() to catch these?

**Comment by seananderson** [comment]
This seems to be a result of `stats::.checkMFClasses`, which gets called by the S3 predict method. However, I believe the same thing happens with any predict method in R, so it's probably best to leave it as is to force the user to maintain exact matching column classes (here sanitizing the column with as.numeric or using arm::rescale). For example:

``` r
library(sdmTMB)
d <- pcod
d$depth <- scale(d$depth)
pcod_spde <- make_spde(d$X, d$Y, n_knots = 50)
m <- sdmTMB(
  data = d, formula = density ~ depth, spde = pcod_spde, 
  family = tweedie(link = "log")
)
d2 <- d
d2$depth <- as.numeric(d2$depth)
predict(m, newdata = d2)
#> Error: variable 'depth' was fitted with type "nmatrix.1" but type "numeric" was supplied

d3 <- subset(d,density > 0)
m <- glm(data = d3, formula = log(density) ~ depth)

d4 <- d3
d4$depth <- as.numeric(d4$depth)
predict(m, newdata = d4)
#> Error: variable 'depth' was fitted with type "nmatrix.1" but type "numeric" was supplied
```

<sup>Created on 2020-09-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ericward-noaa** [comment]
Agreed - let's leave as is. Thanks for looking at this
