### ISSUE TITLE
Adding `getsd = TRUE` to `sdmTMBcontrol`

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [pbs-assess/sdmTMB#311]
I'd like to use sdmTMB to build a model without running it, so that I can more easily diagnose issues during convergence.  I think the easiest way to do that is add `getsd=TRUE` to `sdmTMBcontrol(.)`, so that users can do `getsd=FALSE, newton_loops = 0, nlminb_loops = 0` to get the build object without running it.  `getsd=FALSE` would then skip `sdreport` and `get_convergence_diagnostics` calls in `sdmTMB`.

Does that sound like a useful PR to do on main branch, or any suggestions on alternative ways to do this?

PS:  using it in this way also requires changing `assert_that` to `validate_that` in the auto-check about the passed value of `nlminb_loops`

**Comment by James-Thorson-NOAA** [comment]
Nevermind, I think I see that `sdmTMB( ..., do_fit = FALSE)` will do what I'm intending.

**Comment by seananderson** [comment]
Yeah, do_fit = FALSE should work. The argument is modelled after what glmmTMB does.
