### ISSUE TITLE
tidy with exponentiate = TRUE returns CIs based on already exponentiated estimate

### ISSUE THREAD

**Issue by maxlindmark** [pbs-assess/sdmTMB#353]
Hi!

I wonder if there's an issue with `tidy.sdmTMB()` and the exponentiate argument. See below for an example on how the CIs look wrong:

``` r
library(sdmTMB)

mesh <- make_mesh(pcod, c("X", "Y"), cutoff = 20)

fit <- sdmTMB(
  density ~ s(depth, by = as.factor(year)), 
  time = "year",
  spatial = "off",
  spatiotemporal = "rw",
  data = pcod, mesh = mesh,
  family = tweedie(link = "log")
)
#> Detected irregular time spacing with an AR(1) or random walk process.
#> Consider filling in the missing time slices with `extra_time`.
#> `extra_time = c(2006, 2008, 2010, 2012, 2014, 2016)`

tidy(fit, conf.int = TRUE)
#> # A tibble: 1 × 5
#>   term        estimate std.error conf.low conf.high
#>   <chr>          <dbl>     <dbl>    <dbl>     <dbl>
#> 1 (Intercept)     2.31     0.276     1.77      2.85

tidy(fit, conf.int = TRUE, exponentiate = TRUE)
#> # A tibble: 1 × 5
#>   term        estimate std.error conf.low conf.high
#>   <chr>          <dbl>     <dbl>    <dbl>     <dbl>
#> 1 (Intercept)     10.1     0.276   14052.    41433.
```

<sup>Created on 2024-06-19 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I wonder if this is due to this [code](https://github.com/pbs-assess/sdmTMB/blob/main/R/tidy.R#L151-L154), because `out$estimate` is already exponentiated [here](https://github.com/pbs-assess/sdmTMB/blob/main/R/tidy.R#L134) (if I run the code for `out$conf.low` and `out$conf.high` manually prior to exponentiating out$estimate the exponentiated estimate fits within the CI)

**Comment by seananderson** [comment]
Thanks! Fixed. I also set `conf.int = TRUE` as the new default and removed the `std.error` if `exponentiate = TRUE` since it no longer reflects the printed parameter space.
