### ISSUE TITLE
Add N for Binomial N

### ISSUE THREAD

**Issue by ericward-noaa** [pbs-assess/sdmTMB#36]
Ideally this is a vector that varies by observation, but at minimum needs to be a single integer that could be applied to all observations. Probably passed in as column name in data frame containing trials? Or even easier, just assume it's N in the data frame

**Comment by seananderson** [comment]
I'd have to dig into how to deal with this internally, but in a perfect world we'd probably match how glm(), lmer(), or glmmTMB() does it:

From glmmTMB:
> Binomial models with more than one trial (i.e., not binary/Bernoulli) can either be specified in the form `prob ~ ..., weights = N`, or in the more typical two-column matrix `cbind(successes,failures)~... form`.

**Comment by ericward-noaa** [comment]
I just incorporated this as a 'size' argument, which is how glmmTMB handles it. This could be modified in the future to be the name of a column in the dataframe, rather than a vector of values representing trials

**Comment by seananderson** [comment]
That sounds reasonable, but am I crazy or is 'size' not part of glmmTMB? https://rdrr.io/cran/glmmTMB/man/glmmTMB.html

**Comment by ericward-noaa** [comment]
No - you're right. They call it 'weights' in the wrapper function,
https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/glmmTMB.R

But then the internal functions call it 'size'. E.g.
https://github.com/glmmTMB/glmmTMB/blob/0b1b3b4fd34293a1ee522b966f7cdac31cbf8905/glmmTMB/R/glmmTMB.R#L10

Happy to do whatever -- we have the 'weights' argument doing something else right now, so it's probably easier to keep it as size.

**Comment by seananderson** [comment]
Maybe we should just do something like this:
https://github.com/glmmTMB/glmmTMB/blob/0b1b3b4fd34293a1ee522b966f7cdac31cbf8905/glmmTMB/R/glmmTMB.R#L124-L146
for consistency with glm, lmer, and glmmTMB and to have one less argument. glmmTMB does the same thing with weights as we do, I think. I think all the internals would remain the same as what you've done, just the front-end interface.

Something broke in the continuous integration check for this commit, but it doesn't seem to be related to the changes. size is fine at the moment though. I'm checking it locally.

**Comment by ericward-noaa** [comment]
I'm having a weird INLA error -- unrelated to the commit that is also breaking things. Specifically about rgdal -- and ok, I'll work on the front end bit today

**Comment by seananderson** [comment]
Yeah, see my latest commits. Something isn’t working with the latest INLA
and rgdal on GitHub actions. It checks fine on my computer.

**Comment by ericward-noaa** [comment]
Ok, I ended up implementing the glmmTMB approach, which is slick and includes a couple options I didn't even think of. So I'm going to close this out, given there's now the following 4 options for dealing with the binomial:

 1. The response (y) could be a factor -> treat as binary following glm
 2. The response (y) could be a matrix cbind(success, failure)
 3. The response (y) could be binary
 4. The response, combined with the 'weights' argument could be (proportions, size)

**Comment by seananderson** [comment]
Sweet, thanks!

**Comment by mbuonanduci** [comment]
I've been able to get the binomial working using approach #4 above. FYI, I could be misreading things, but I think the binomial residuals function may need to be updated to account for the weights.

**Comment by ericward-noaa** [comment]
Thanks Michele - there's an 'n' argument in the residuals for the Binomial that should allow you to enter the weights. I haven't tested it with size values > 1, but have confirmed the others are giving the same results. Form 2 has something else going on that I'm in the process of fixing -- but others should be ok:

library(sdmTMB)

# Example from ?sdmTMB
d <- subset(pcod, year >= 2011)
pcod_binom <- d
pcod_binom$present <- ifelse(pcod_binom$density > 0, 1L, 0L)
pcod_spde <- make_mesh(d, c("X", "Y"), cutoff = 30)

# Form 1
pcod_binom$fac_present = as.factor(pcod_binom$present)
fit1 <- sdmTMB(fac_present ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
                data = pcod_binom, time = "year", spde = pcod_spde,
                family = binomial(link = "logit"),mgcv=FALSE)
set.seed(123)
resid1 = residuals(fit1)

# Form 2
pcod_binom$success = pcod_binom$present
pcod_binom$fail = 1 - pcod_binom$success
m_bin <- sdmTMB(cbind(success,fail) ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
                data = pcod_binom, time = "year", spde = pcod_spde,
                family = binomial(link = "logit"), mgcv=FALSE)
set.seed(123)
resid2 = residuals(m_bin)

# Form 3
fit3 <- sdmTMB(present ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
                data = pcod_binom, time = "year", spde = pcod_spde,
                family = binomial(link = "logit"))
set.seed(123)
resid3 = residuals(fit3)

# Form 4
pcod_binom$rate = pcod_binom$success
fit4 <- sdmTMB(rate ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
               data = pcod_binom, time = "year", spde = pcod_spde,
               family = binomial(link = "logit"), weights=rep(1,nrow(pcod_binom)))
set.seed(123)
resid4 = residuals(fit4, n = rep(1,nrow(pcod_binom)))

**Comment by mbuonanduci** [comment]
Thanks Eric!

One thing I noticed when looking at the internal `qres_binomial` function. Should this line potentially need to be modified from this:
`u <- stats::runif(n = length(y), min = min(a, b), max = max(a, b))`

to this:
`u <- stats::runif(n = length(y), min = pmin(a, b), max = pmax(a, b))`

in order to get element-wise min and max?

**Comment by ericward-noaa** [comment]
@mbuonanduci  thanks for catching this. Yes, I intended this to be pointwise, but the code wasn't doing that. I've fixed it with your suggestion, and just pushed the change -- so should be working ok now. Sorry about that!
