### ISSUE TITLE
Problem in SVC vignette

### ISSUE THREAD

**Issue by joshcullen** [pbs-assess/sdmTMB#363]
I was running through the examples provided in the "**Fitting spatial trend models with sdmTMB**" vignette and ran into an error when trying to make predictions on new data using the built-in `qcs_grid` dataset. The fitted model includes a spatially varying effect of `scaled_year`, but the `qcs_grid` dataset doesn't include a column for year. This may have been a recent change given that the vignette appears to have last been rendered ~1.5 years ago.

Similar to the examples in the README, would `nd <- replicate_df(qcs_grid, "year", unique(pcod$year))` be a suitable workaround for this example?

**Comment by ericward-noaa** [comment]
Yes -- sorry about the vignette not being updated, we'll work on that. Your solution seems like a good workaround

**Comment by seananderson** [comment]
Where are you viewing this vignette? That line should already be in there and the (web-only) vignette should get built with every push to the main branch. This is the official version:

https://pbs-assess.github.io/sdmTMB/articles/web_only/spatial-trend-models.html

**Comment by joshcullen** [comment]
Huh, you're right Sean. Maybe it's something with how the `README.Rmd` file was rendered?

I clicked on the link at the end of the SVC section of the README page (https://pbs-assess.github.io/sdmTMB/index.html#spatially-varying-coefficients-svc), which then brought me to the vignette dated 2023-01-03. But using the link you included or accessing from the `Articles` dropdown takes me to the updated version from last month.

**Comment by seananderson** [comment]
Ah, it turns out all the links in the README file (and most links in the help files) link to versions without `web_only` in the URL and those linked to old cached versions. I wonder if pkgdown changed the default behaviour. What a mess. I'll figure something out. Thanks for pointing this out!

**Comment by seananderson** [comment]
Indeed it looks like the suggested folder for web-only articles changed from `web_only` to `articles`. I've renamed the folder, removed links within the docs to the `web_only` URLs, and pushed the updates to GitHub. Unfortunately, now any links to the `web_only` versions will become out of date since GitHub pages seems to cache old versions. 🤷‍♂️ Eventually I'll trash the old commits on the GitHub pages branch.

**Comment by joshcullen** [comment]
Sounds good. Thanks for looking into this so quickly!
