### ISSUE TITLE
NA/NaN gradient evaluation issue encountered when running the sdmTMB using Beta family

### ISSUE THREAD

**Issue by xiacong2019** [pbs-assess/sdmTMB#364]
Hi,
when I tried to run this code, 

data <-  readRDS("./sample.rds")
weights <- data$weights
mesh <- make_mesh(data, c("x", "y"), cutoff = 10000)
model_new <- sdmTMB(
  response ~ predictor + (1 | country ),
  mesh = mesh,
  data = data,
  family = Beta(),
  spatial = "on", weights = weights)

It reported this error:
Error in stats::nlminb(start = tmb_obj$par, objective = tmb_obj$fn, gradient = tmb_obj$gr,  : 
  NA/NaN gradient evaluation

I have reinstalled the Matrix, TMB, and sdmTMB packages from source but no use. I would appreciate it if you could help me for fixing this error.

**Comment by xiacong2019** [comment]
And I also want to ask if there is any other means to fit a spatial glmm with overdispersion in sdmTMB?

**Comment by seananderson** [comment]
Can you provide a reproducible example? Perhaps upload the data somewhere or save a small version with dput() and paste it here or simulate some data?

Regarding other possible approaches: you could use a binomial family with a random intercept level for each row of data to account for additional dispersion. Make a column that is a factor with levels from 1 to the number of rows of data and add that column as a random intercept.

**Comment by xiacong2019** [comment]
Yeah, sure! I share the data with you via Google Drive. Please download from this link: https://drive.google.com/drive/folders/1lP9yxlpa8cyiWxz0HPHTTuBR7Tp1GqEe?usp=drive_link
And thanks for your suggestion about using random intercept to account for dispersion! I will also have a try！

**Comment by xiacong2019** [comment]
> Can you provide a reproducible example? Perhaps upload the data somewhere or save a small version with dput() and paste it here or simulate some data?
> Yeah, sure! I share the data with you via Google Drive. Please download from this link: https://drive.google.com/drive/folders/1lP9yxlpa8cyiWxz0HPHTTuBR7Tp1GqEe?usp=drive_link
> Regarding other possible approaches: you could use a binomial family with a random intercept level for each row of data to account for additional dispersion. Make a column that is a factor with levels from 1 to the number of rows of data and add that column as a random intercept.
Thanks for your suggestion about using random intercept to account for dispersion! I will have a try！

**Comment by seananderson** [comment]
I still don't have access to that Google Drive folder. If you can give me access (email is [here](https://github.com/pbs-assess/sdmTMB/blob/main/DESCRIPTION#L6)) I can have a look at this. Otherwise, I'm closing this for now. Feel free to re-open.

Here's an example with the Beta family:

``` r
library(sdmTMB)
set.seed(123)
predictor_dat <- data.frame(
  X = runif(2000), Y = runif(2000),
  a1 = rnorm(2000)
)
mesh <- make_mesh(predictor_dat, xy_cols = c("X", "Y"), cutoff = 0.1)
sim_dat <- sdmTMB_simulate(
  formula = ~ 1 + a1,
  data = predictor_dat,
  mesh = mesh,
  family = Beta(),
  range = 0.5,
  phi = 15,
  sigma_O = 0.2,
  seed = 42,
  B = c(0.2, -0.4)
)
fit <- sdmTMB(observed ~ a1, data = sim_dat, mesh = mesh, family = Beta())
fit
#> Spatial model fit by ML ['sdmTMB']
#> Formula: observed ~ a1
#> Mesh: mesh (isotropic covariance)
#> Data: sim_dat
#> Family: Beta(link = 'logit')
#>  
#>             coef.est coef.se
#> (Intercept)     0.14    0.09
#> a1             -0.39    0.01
#> 
#> Dispersion parameter: 14.99
#> Matérn range: 0.41
#> Spatial SD: 0.21
#> ML criterion at convergence: -1349.831
#> 
#> See ?tidy.sdmTMB to extract these values as a data frame.
```

<sup>Created on 2024-09-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Note that high dispersion (phi above) equates to low observation variance for the Beta family here.
