### ISSUE TITLE
Add penalized complexity prior

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#39]
See code example in p 74-77 of https://arxiv.org/abs/2103.09929

Allows for matching INLA; may help convergence in some cases.

**Comment by seananderson** [comment]
I've worked on this here: https://github.com/pbs-assess/sdmTMB/commit/8281b759b203eaebc85c8fe9080cea211d4e1a63

It appears to be working. It doesn't do much for simulated data that are easily fit, but it does seem to have influence on real data (like the pcod example data) where the spatial range is less well identified. In that case, it speeds up fitting. Presumably this could help a lot with convergence in some cases. It would also help for comparison with INLA.

I haven't thought through whether it makes sense to be applying this to both the spatial and spatiotemporal random fields when they share a single range parameter.

It might be worth having a 'how do I speed up or help my model converge vignette' eventually. This, the normalize option, lower resolution meshes, less complex random field setups, priors on the fixed effects, ...

**Comment by seananderson** [comment]
Helpful paper https://arxiv.org/pdf/1503.00256.pdf

**Comment by seananderson** [comment]
After playing with this a bit more and reading the above paper, this is seems to be working nicely.

Basically, the random field SD and the range are highly correlated. The PC prior jointly bounds sigma from getting too big and range from getting too small.

The prior keeps the model in the yellow zone:
![image](https://user-images.githubusercontent.com/19349/119944081-b202a380-bf48-11eb-9cf1-77981598547a.png)

It really stabilizes the model and tightens up the range and random field SD parameters for survey data. The preprint illustrates that it should still have good coverage as long as the priors aren't off by orders of magnitude. Even a relatively light PC prior seems to help a lot.

It's set up as a vector of length 4 of penalized complexity prior values. Order is `c(a, b, c, d)` where `P(range < a) = b` and `P(sigma > c) = d`.

Code for the above with credit to https://arxiv.org/abs/2103.09929 for the TMB version of the PC prior function:

```r
library(ggplot2)

pow <- function(x, power) x^power

matern_pc_prior <- function(logtau, logkappa, matern_pars, give_log = FALSE) {
  matern_par_a <- matern_pars[1] # ; // range limit: rho0
  matern_par_b <- matern_pars[2] # ; // range prob: alpha_rho
  matern_par_c <- matern_pars[3] # ; // field sd limit: sigma0
  matern_par_d <- matern_pars[4] # ; // field sd prob: alpha_sigma
  d <- 2. # ;  // dimension
  lambda1 <- -log(matern_par_b) * pow(matern_par_a, d / 2.)
  lambda2 <- -log(matern_par_d) / matern_par_c
  range <- sqrt(8.) / exp(logkappa)
  sigma <- 1. / sqrt(4. * 3.14159265358979 * exp(2. * logtau) * exp(2. * logkappa))
  penalty <- (-d / 2. - 1.) * log(range) - lambda1 *
    pow(range, -d / 2.) - lambda2 * sigma
  jacobian <- -logtau - 2. * logkappa
  penalty <- penalty + jacobian
  if (!give_log) penalty <- exp(penalty)
  data.frame(sigma = sigma, range = range, penalty = penalty)
}

d <- expand.grid(
  logtau = seq(-1, 1, length.out = 60),
  logkappa = seq(-5, 5, length.out = 60)
)
out <- purrr::map2_dfr(
  d$logtau,
  d$logkappa,
  function(x, y) {
    # play with these matern_pars PC prior settings:
    # A vector of length 4 of penalized complexity
    # prior values. Order is `c(a, b, c, d)` where `P(range < a) = b` and
    # `P(sigma > c) = d`.
    matern_pc_prior(x, y, matern_pars = c(2, 0.05, 1, 0.05), give_log = TRUE)
  }
)
ggplot(out, aes(sigma, range, colour = penalty)) +
  geom_tile(size = 5) +
  scale_x_log10() +
  scale_y_log10() +
  # scale_colour_viridis_c(limits = c(-10000, 0))
  scale_colour_viridis_c() +
  labs(colour = "PC prior\npenalty")
```

Fitting experiments:

```r
library(ggplot2)
library(sdmTMB)
d <- pcod
pcod_spde <- make_mesh(d, c("X", "Y"), cutoff = 30)
m <- sdmTMB(
  data = d, formula = density ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
  time = "year", spde = pcod_spde, family = tweedie(link = "log")
)

m_pc <- sdmTMB(
  data = d, formula = density ~ 0 + as.factor(year) + depth_scaled + depth_scaled2,
  time = "year", spde = pcod_spde, family = tweedie(link = "log"),
  matern_prior_O = c(5, 0.05, 3, 0.05),
  matern_prior_E = c(5, 0.05, 2, 0.05)
)

tidy(m, "ran_pars", conf.int = TRUE)

tidy(m_pc, "ran_pars", conf.int = TRUE)
```

![image](https://user-images.githubusercontent.com/19349/119945579-7f59aa80-bf4a-11eb-8673-a08e9e25470f.png)

It runs ~10% faster too.

**Comment by seananderson** [comment]
All that's left on this is thinking about whether there's a better interface to it (and also whether we want the Jacobian adjustment for penalized maximum likelihood estimation and if applying the PC prior to both the spatial and spatiotemporal fields makes sense when they share a range).

Given the recent success and interface to predicting with tmbstan, I'm wondering about adding basic prior specification for all the parameters. The betas (b_j) already have priors via `penalties`. I'm wondering about a named list of optional priors for everything else, and that could include these. That said, the need for 4 values specified per random field could be cumbersome enough to warrant their own arguments a currently set up.

Something like:

```r
priors = list(phi = 3, ar1_rho = 2, tweedie_p = 2)
```

where the numbers correspond to SDs of (sometimes half) normal distributions with defined means (usually 0, except `tweedie_p`). Alternatively, we could use betas for ar1_rho and (shifted beta) tweedie_p.

If doing the above with the PC prior, where:

`P(range < a) = b`
`P(sigma > c) = d`.

Setting the probabilities all to 0.05 and then just letting the user specify a and c above:

```r
priors = list(range = 4, sigma_O = 3, sigma_E = 2)
```

So, might look like:

```r
priors = list(range = 4, sigma_O = 3, sigma_E = 2, phi = 3, ar1_rho = 2, tweedie_p = 2)
```

Optionally:

```r
priors = list(range = 4, sigma_O = 3, sigma_E = 2, phi = 3, ar1_rho = 2, tweedie_p = 2, b_j = c(NA, 1, 1, 1, 1)
```

**Comment by ericward-noaa** [comment]
This seems great. I think the PC prior on both sigma_E and sigma_O seems complicated with the shared kappa / range. I imagine if you used the PC prior on one, it'd be informative wrt the other? Attaching an extension of your models with only 1 PC prior used -- results similar to eachother and your m_pc model.

![image](https://user-images.githubusercontent.com/5046884/121729720-a31d0480-caa3-11eb-8446-9a85ae2b03ef.png)

Re: Jacobian, I saw in ?optimize that Stan doesn't use the Jacobian adjustment for bounded parameters -- I don't know if that applies to variances in sdmTMB, where the prior has a bound but parameters are in transformed space and do not. Is part of this decision whether we're interpreting the output as ML or Bayesian?

Re: syntax, I think the list() options are fine. I don't know that it's worth doing, but I like the syntax that brms() uses, where there's a prior class and priors can be specified as strings or objects, e.g. prior(normal(0,1)) or prior("normal(0,1))"). I don't know how to evaluate strings in TMB, but we could have a function that parses them into allowed functions / parameters.

**Comment by seananderson** [comment]
I think doing one or the other (sigmaO or sigmaE PC prior) would work fairly well since the range gets constrained and is strongly correlated with sigmaO and sigmaE but it still lacks penalizing the missing sigma. I wonder what they do in the INLA world. I imagine they just don't share the range if you have multiple fields, which is also an option. I think the only reason for sharing the range in VAST etc. is that the range is hard to estimate, but the priors help substantially with that.

Regarding the Jacobian adjustments, I finally wrote out a simulation to prove to myself when you do/do not want it. https://github.com/pbs-assess/sdmTMB/blob/pc-prior/inst/jacobian-tests.R

Conclusion: you only want the adjustments if you're using Stan MCMC sampling, so we'll need a toggle to turn that on/off.

Output from the script:

```r
  type                  stan_mean stan_median nlminb sims_mean sims_median
  <chr>                     <dbl>       <dbl>  <dbl>     <dbl>       <dbl>
1 No prior                  0.922       0.922  0.905     0.908       0.905
2 Prior no adjustment       0.918       0.914  0.902     0.904       0.902
3 Prior with adjustment     0.922       0.918  0.906     0.909       0.906
4 Prior limits              0.922       0.918  0.902     0.902       0.902
```

(Prior limits avoids the exp(log_sigma), uses lower and upper, and should always be 'correct' in the above.)

We do that kind of brms-style prior parsing in glmmfields. I'm not sure if it's worth the complexity since we have to enforce a single prior type per parameter (or hand code various options) whereas brms gets away with it since it creates code on the fly. That said, we could probably code a couple options for some (e.g., half-normal or half-t for the SD, normal on transformed AR1 rho or beta on untransformed rho) and stop() before fitting if something 'illegal' gets used. Then it would be worth having a more verbose syntax.

**Comment by seananderson** [comment]
Also, unless I'm missing something, we probably want to toggle the Jacobian adjustment currently in the PC prior off unless going to Stan:
https://github.com/pbs-assess/sdmTMB/blob/7c4def7c98fe9ac580d329843dd0bec91c0fbfa4/src/sdmTMB.cpp#L114-L133

**Comment by seananderson** [comment]
P.S. the 'trick' for getting easy-to-read text-based options within TMB is to use `enum`:

https://github.com/pbs-assess/sdmTMB/blob/7c4def7c98fe9ac580d329843dd0bec91c0fbfa4/src/sdmTMB.cpp#L183-L200
https://github.com/pbs-assess/sdmTMB/blob/8d02387ee938ce4468d81d8c0bda4c0c1d367da7/R/enum.R#L1-L19
https://github.com/pbs-assess/sdmTMB/blob/8d02387ee938ce4468d81d8c0bda4c0c1d367da7/R/fit.R#L513-L515

which is a trick I borrowed after reading the glmmTMB source code.
