### ISSUE TITLE
Let user specify a custom map list

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#43]
Would allow for testing of turning off spatial estimation, for example, to compare to a standard GLMM.

**Comment by ericward-noaa** [comment]
This is a great idea and happy to work on it. At quick glance, there's only a handful of things that'd need to be mapped off to turn off spatial information: ln_H_input, ar1_phi, ln_tau_E, epsilon_st, ln_tau_O, omega_s, ln_tau_O_trend, omega_s_trend

Does it makes sense to have a boolean argument (e.g. no_space or something) the user could change to turn these on/off? Or should the list be passed in?

**Comment by kellijohnson-NOAA** [comment]
Is there a way we can do it that users do not have to remember all of the names to get to the standard glmm? Like the default is everything and a standard glmm is an empty vector or argument?

**Comment by ericward-noaa** [comment]
Yeah -- I think the boolean on/off I was thinking about is the same as what you're suggesting -- I'll try it out

**Comment by seananderson** [comment]
I have the map thing working on my local copy right now. I can also include a boolean to just turn off all random field stuff. The code is already there in the initial phase fit without random effects.

**Comment by ericward-noaa** [comment]
Beat me to it -- I'm working out some kinks in my local copy, but not quite working

**Comment by seananderson** [comment]
OK, this is in there now as the logical `map_rf`. Setting `map_rf = TRUE` will fix all spatial and spatiotemporal elements to 0 resulting in a standard GLM/GLMM.
