### ISSUE TITLE
Tweak beta-epsilon priors / Implement lower and upper bounds

### ISSUE THREAD

**Issue by ericward-noaa** [pbs-assess/sdmTMB#48]
* Get rid of weird transformations, add bounds
* Bounds need to go to control list? 

Prior args here
https://github.com/pbs-assess/sdmTMB/blob/b5529d945f01b4214cbf277e154818815acb8bcd/R/fit.R#L361
https://github.com/pbs-assess/sdmTMB/blob/b5529d945f01b4214cbf277e154818815acb8bcd/src/sdmTMB.cpp#L400-L413
https://github.com/pbs-assess/sdmTMB/blob/b5529d945f01b4214cbf277e154818815acb8bcd/src/sdmTMB.cpp#L462-L480
Modify args to nlminb:
 https://github.com/pbs-assess/sdmTMB/blob/b5529d945f01b4214cbf277e154818815acb8bcd/R/fit.R#L800

**Comment by seananderson** [comment]
We should probably add `lower` and `upper` to the `sdmTMBcontrol()` list. Each could default to NULL but take a named list and then prior to optimization, create a vector of `-Inf` and `Inf` and replace any with the matching entries from `lower` and `upper`.

**Comment by seananderson** [comment]
Priors and bounds are in the 'priors-experimental' branch now:
https://github.com/pbs-assess/sdmTMB/blob/priors-experimental/tests/testthat/test-bounds.R
https://github.com/pbs-assess/sdmTMB/blob/priors-experimental/tests/testthat/test-priors.R
https://github.com/pbs-assess/sdmTMB/blob/priors-experimental/R/priors.R

I started updating the NEWS file https://github.com/pbs-assess/sdmTMB/blob/priors-experimental/NEWS.md#sdmtmb-00169000
