### ISSUE TITLE
Adding standard errors for model predictions

### ISSUE THREAD

**Issue by jkatzenberger** [pbs-assess/sdmTMB#5]
Currently the sdmTMB version of predict does not support an argument for adding standard errors to the predictions.  

It would be great if you could enable this option in the package. 

Thanks a lot and best wishes! 
Jakob

**Comment by seananderson** [comment]
Are you looking for standard errors on predictions at the original data locations or on new location predictions? Either is possible but because of the way the code is written they will take a bit of different manipulation on the R and C++ side. In other words, which should I do first?

**Comment by jkatzenberger** [comment]
Wow, that was quick! Thanks so much for your effort. 
Getting standard errors on predictions at new locations would be what I am looking for right now...

**Comment by seananderson** [comment]
Take a look at the new example in the predict function (`se_fit = TRUE`). You should now be able to calculate standard errors on predictions at new locations. I haven't simulation tested these yet to make sure they are right. You might find that they are unusably slow right now for large data sets or high-resolution predictions. The alternative would be to do piece-wise predictions like those that are done in the VAST package. Each location would get the prediction based on the nearest knot from the spatial random effects. Right now I'm using the full projection matrix from INLA and that makes for a lot of little points to do the delta method on.

**Comment by jkatzenberger** [comment]
Great, thank you very much!
