### ISSUE TITLE
Make sdmTMB() work without a mesh if all fields are turned off

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#59]
Work in 'sim2' branch where `spatial = 'off'` and `spatiotemporal = 'off'` does this (same as `map_rf = TRUE`. Good suggestion by @joenomiddlename. Will require filling in dummy mesh data and changing a few things that assume a mesh is present (e.g. finding the INLA 'A' matrix).

**Comment by seananderson** [comment]
I just added a hack that creates a fake mesh if there are no random fields. Not super elegant, but for a small overhead it's guaranteed to work everywhere. I also cleaned up `print()` if there are no random fields.

```r
fit <- sdmTMB(
  density ~ as.factor(year) + s(depth, k = 3), 
  data = pcod_2011, 
  family = tweedie(link = "log"), 
  spatial = "off", spatiotemporal = "off"
)
```

```
Model fit by ML ['sdmTMB']
Formula: density ~ as.factor(year) + s(depth, k = 3)
Mesh: NULL
Data: pcod_2011
Family: tweedie(link = 'log')
                    coef.est coef.se
(Intercept)             2.50    0.16
as.factor(year)2013    -0.05    0.18
as.factor(year)2015     0.34    0.18
as.factor(year)2017    -0.59    0.19
sdepth                  5.02    0.39

Smooth terms:
           Std. Dev.
sds(depth)     88.95

Dispersion parameter: 15.09
Tweedie p: 1.61
ML criterion at convergence: 2973.045
```

**Comment by ericward-noaa** [comment]
I did similar when working on the CAR branch
https://github.com/pbs-assess/sdmTMB/blob/3402fad5e01724c491c3eb09bd0c7bf5937464ec/R/fit.R#L491
but this version is better, so the CAR hack can get deleted
