### ISSUE TITLE
Standardize column names in prediction data frame

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#7]
With the recently added spatial-varying slopes random fields (thanks @eric-ward!) the prediction data frame is getting complicated. Might be a good time to put some more thought into what they should be called. 

The current setup:
`est` = Complete estimate in link space (everything is in link space)
`est_fe` = Estimate from fixed effects
`est_re_s` = Spatial random effect estimates
`est_re_s_trend` = Spatial trend estimates (slope * time)
`est_re_st` = Spatiotemporal random effect estimates
`re_s_trend` = The spatial trend slopes themselves

It occurred to me that maybe it makes more sense just to name these columns based on the symbols that have become a bit of a convention and are used in the TMB code. 

Therefore, 

`est_re_s` would instead be `omega_s`
`est_re_st` would be `epsilon_st`

These are the realizations of these random effects at the prediction locations.

This makes me think we should come up with a symbol for the slope random field. Anything could do. Maybe gamma or psi or the always-cool-sounding zeta?

It probably doesn't make sense to show just the spatially-varying slope * time realizations and since that doesn't make much sense without the intercept included. I was wondering if instead we should make a column that is the sum of all the random effects. In the case of spatially varying slopes this would be the spatially varying intercept plus the spatially varying slope * time. In other cases this might be omega_s + epsilon_st. And in other cases this would just be the same as omega_s or epsilon_st. What to call this? `est_re`?

Then we could have `est_fe` representing the predictions just from all the fixed effects. This currently includes the predictions from the time varying effects, which technically aren't fixed effects but since they are constant across space it makes sense to me to include them here. Basically these are the predictions that don't include any random fields. An alternative would therefore be `est_rf` and `est_non_rf` for random field estimates and non random field estimates. Maybe that's nicer and avoids the whole fixed-effect-random-effect jargon problem.

Finally, we have `est`, which represents the some of all the effects in link space.

OK, after that stream of consciousness, one proposal would be:

`est` = Complete estimate in link space (everything is in link space)
`est_non_rf` = Estimate from everything that isn't a random field
`est_rf` = Estimate from all random fields combined together
`omega_s` = Spatial (intercept) random field that is constant through time
`epsilon_st` = Spatiotemporal (intercept) random fields (could be independent draws each year or AR1)
`zeta_s` = Spatial slope random field

**Comment by eric-ward** [comment]
In terms of naming, I think this is all more clear than the status quo. 'zeta_s' for the spatial slope random field would be good -- I think most of these are included in the 'index standardization' vignette, but it'd be good to have examples of each of these being extracted from the predict data frame if not already there (and maybe even the math notation to accompany them in the vignette or somewhere else?). I'm happy to help with this...

**Comment by lewisab** [comment]
This seems better.  I was getting confused going between the new proposed names and the ones in the spatial trends vignette. What was the former equivalent of est_rf?

**Comment by seananderson** [comment]
> What was the former equivalent of est_rf

There is none currently. I need to add them up in the .cpp file first.

**Comment by seananderson** [comment]
As a follow-up, although there is no `est_rf` right now, in the case of the spatial trends model `est_re_s_trend` is the same thing if there aren't any other spatiotemporal random effects.

**Comment by lewisab** [comment]
Oh, I see now where you wrote about including this as a new output, sorry. Thanks Sean for the clarification.

**Comment by seananderson** [comment]
This is done now and matches the above format. Also, `predict.sdmTMB()` by default returns just the data frame. No need for `$data` now.

est = Complete estimate in link space (everything is in link space)
est_non_rf = Estimate from everything that isn't a random field
est_rf = Estimate from all random fields combined together
omega_s = Spatial (intercept) random field that is constant through time
epsilon_st = Spatiotemporal (intercept) random fields (could be independent draws each year or AR1)
zeta_s = Spatial slope random field
