### ISSUE TITLE
Parallel processing

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#74]
I followed [these](https://stackoverflow.com/a/70664229) instructions (M1 Mac specific, I think).

Then worked on [this](https://github.com/pbs-assess/sdmTMB/tree/parallel) branch.

Tested in [this](https://github.com/pbs-assess/sdmTMB/blob/parallel/inst/test-open-mp.R) script.

Depends strongly on the model, but I'm getting ~50% speed ups up to about to 3-4 threads usually.
<img width="577" alt="image" src="https://user-images.githubusercontent.com/19349/159626370-4984e375-98b1-4be1-a7e5-aeccd0f0d51d.png">

Currently, `sdmTMBcontrol()` grabs the `sdmTMB.cores` option value and defaults to 1. E.g., `options(sdmTMB.cores = 4)`

I've only enabled it for Unix for now because the glmmTMB experience makes it look complicated for Windows on CRAN.

After testing how this behaves on Windows, non-openMP enabled Unix machines, and various CI routines, I'll merge it into the main branch.

```r
library(sdmTMB)
mesh <- make_mesh(pcod_2011, c("X", "Y"), cutoff = 10)
options(sdmTMB.cores = 4)
fit <- sdmTMB(density ~ 0 + depth_scaled + depth_scaled2 + as.factor(year),
  data = pcod_2011, time = "year", mesh = mesh, family = tweedie(link = "log"))
```

**Comment by sschooler** [comment]
Is it possible to add parallel processing support for windows?
