### ISSUE TITLE
Stacking fold IDs

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#75]
I integrated the stacking branch a couple days ago.

One thing I wondered about was whether all the folds need to be the same. I added a check:
https://github.com/pbs-assess/sdmTMB/blob/5de93521ddfaabf42e2c51e8ecfed5d29b89d89a/R/stacking.R#L62-L67

I would think that it would be preferable if all the folds were the same to reduce an extra source of variation, but it seems necessary to me given the way the function is currently set up to allow subsetting by fold IDs. Or maybe it's okay as long as it's clear that the filtering is based on the fold IDs in the first fold? In that case, we could change that stop to a warning.

**Comment by ericward-noaa** [comment]
I agree -- if the fold ids differed across models, that's adding random variation. So let's keep it the way you have it!
