### ISSUE TITLE
Add vignette on using visreg to visualize conditional effects

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#83]
See `?visreg_delta` for some examples

**Comment by jindivero** [comment]
Just wanted to let you know that I'm working on this!
https://github.com/pbs-assess/sdmTMB/blob/f7e7251494cb4d0b65a936829ca44e4735b3f612/julia-vignettes/visualization_with_ggeffects.Rmd

**Comment by seananderson** [comment]
This is on the latest main or dev branch version? The examples in `?visreg_delta` should be working.

**Comment by jindivero** [comment]
I think the latest main branch version. I can try with the dev branch

**Comment by jindivero** [comment]
I'm not able to get the visreg_delta examples to work on either the main branch or the dev branch. Is there something else I can try?

**Comment by jindivero** [comment]
I'm also not able to get the ggeffect example that you emailed to work. I'm getting the error: "Warning: Cannot coerce data into a data frame. No data will be returned. Warning: Could not access model information. Can't compute marginal effects, 'effects::Effect()' returned an error."

**Comment by seananderson** [comment]
Is it possible you have an old version of the package still loaded in your R session? Does the following work for you? The important part below would be restarting the R session. An advantage to installing locally from the sdmTMB RStudio project (e.g., `devtools::load_all()` or `devtools::install()`) is it would take care of reloading the package or you. Otherwise, you may need to restart the session with this or any R package.

```r
remove.packages("visreg")
remove.packages("sdmTMB")

install.packages("visreg")
remotes::install_github("pbs-assess/sdmTMB", force = TRUE)

# assuming on RStudio, or Session->Restart R,
# or restart your R session some other way...
rstudioapi::restartSession()

library(sdmTMB)
fit <- sdmTMB(
  density ~ s(depth_scaled),
  data = pcod_2011, mesh = pcod_mesh_2011,
  family = tweedie()
)
visreg::visreg(fit, xvar = "depth_scaled")
```

![](https://i.imgur.com/cFFj1Xj.png)

``` r
sessionInfo()
#> R version 4.1.3 (2022-03-10)
#> Platform: aarch64-apple-darwin20 (64-bit)
#> Running under: macOS Monterey 12.3.1
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] sdmTMB_0.0.24.9004
#> 
#> loaded via a namespace (and not attached):
#>  [1] styler_1.7.0        zoo_1.8-9           xfun_0.31          
#>  [4] TMB_1.8.1           purrr_0.3.4         splines_4.1.3      
#>  [7] lattice_0.20-45     glmmTMB_1.1.3       vctrs_0.4.1        
#> [10] generics_0.1.2      htmltools_0.5.2     yaml_2.3.5         
#> [13] mgcv_1.8-40         survival_3.3-1      utf8_1.2.2         
#> [16] rlang_1.0.2         R.oo_1.24.0         pillar_1.7.0       
#> [19] nloptr_2.0.0        glue_1.6.2          withr_2.5.0        
#> [22] R.utils_2.11.0      sp_1.4-7            multcomp_1.4-18    
#> [25] emmeans_1.7.3       R.cache_0.15.0      lifecycle_1.0.1    
#> [28] stringr_1.4.0       R.methodsS3_1.8.1   mvtnorm_1.1-3      
#> [31] codetools_0.2-18    coda_0.19-4         evaluate_0.15      
#> [34] knitr_1.39.1        fishMod_0.29        fastmap_1.1.0      
#> [37] parallel_4.1.3      fansi_1.0.3         visreg_2.7.0       
#> [40] highr_0.9           TH.data_1.1-0       Rcpp_1.0.8.3       
#> [43] INLA_22.03.16       xtable_1.8-4        fs_1.5.2           
#> [46] lme4_1.1-29         digest_0.6.29       stringi_1.7.6      
#> [49] numDeriv_2016.8-1.1 grid_4.1.3          cli_3.3.0          
#> [52] tools_4.1.3         sandwich_3.0-1      magrittr_2.0.3     
#> [55] tibble_3.1.7        crayon_1.5.1        pkgconfig_2.0.3    
#> [58] ellipsis_0.3.2      MASS_7.3-56         Matrix_1.4-1       
#> [61] estimability_1.3    reprex_2.0.1        assertthat_0.2.1   
#> [64] minqa_1.2.4         rmarkdown_2.14      rstudioapi_0.13    
#> [67] boot_1.3-28         nlme_3.1-157        compiler_4.1.3
```

<sup>Created on 2022-05-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
```

**Comment by jindivero** [comment]
Thank you! The visreg example is working now, but still not ggeffect.

**Comment by jindivero** [comment]
Hi! Couple other questions that have come up:
--Is there an example dataset that has two continuous explanatory variables (another one besides depth, maybe temp or something)? Visreg has some options for plotting effects of two variables but it works better with continuous rather than the categorical year
--Visreg does not like plotting any contrast plots from the sdmTMB output. I've tried a few different models and get a few different errors: if using s(depth_scaled) in model, get error about not recognizing function s; if I use just depth_scaled in the model, get "Error in UseMethod("vcov"): no applicable method for 'vcov' applied to an object of class "sdmTMB"; and same with using poly(depth_scaled). But, conditional plots work fine, and so do 2d plots.

**Comment by seananderson** [comment]
There is bottom temperature (and dissolved oxygen) associated with that dataset, but it's not in the package data. We could add that. Sometimes I've also treated year as continuous for that purpose.

I haven't set it up to work with `type = 'contrast'`. I'd have to look into what's needed for that. I think that may be the same as what ggeffects::ggeffect is doing, which may be a better interface. Ultimately, I wonder if ggeffects::ggeffect and ggeffects::ggpredict (over conditional visreg; not yet working) are the way to go.

If the ggeffect example isn't working that is likely because you have the main branch installed and not the dev branch. If you have installed the dev branch, perhaps you need to restart your R session?

**Comment by ericward-noaa** [comment]
Julia - I was thinking we could just simulate the data -- maybe something with an interesting seasonal and/or hourly pattern -- hourly example here:

```

# make fake predictor(s) and sampling locations:
N = 300
predictor_dat <- data.frame(
  X = runif(N), Y = runif(N),
  log_depth = rnorm(N,mean=2,sd=1), 
  year = rep(1:6, each = 50),
  hour = sample(1:24, size = N, replace=T)
)
predictor_dat$hour_effect = 0.2 * sin(2*pi/365*predictor_dat$hour)
predictor_dat$log_depth2 = predictor_dat$log_depth^2

mesh <- make_mesh(predictor_dat, xy_cols = c("X", "Y"), cutoff = 0.1)

sim_dat <- sdmTMB_simulate(
  formula = ~ hour_effect + log_depth + log_depth2,
  data = predictor_dat,
  time = "year",
  mesh = mesh,
  family = gaussian(),
  range = 0.5,
  sigma_E = 0.1,
  phi = 0.1,
  sigma_O = 0.2,
  seed = 42,
  B = c(0.2, -0.4, 0.02) # hour effect, linear depth, quadratic depth
)

```

**Comment by jindivero** [comment]
Gotcha, thanks! I'm getting this error with that sdmTMB_simulate() part: "Error: Number of specified fixed-effect `B` parameters does not match model matrix columns implied by the formula." I double checked I'm using the dev branch version.

**Comment by seananderson** [comment]
In the code above, there's one more B coefficient needed to match the formula/model matrix. Should be intercept, hour effect, linear depth, quadratic depth.

**Comment by ericward-noaa** [comment]
Sorry -- my fault. I meant to not include intercept, so formula should be 

`0 + hour_effect + log_depth + log_depth2`

**Comment by jindivero** [comment]
Thanks! Now I'm getting  "Error in terms(formula) : object 'hour_effect' not found", but I've checked and re-run the code multiple times and hour_effect is definitely a column in the predictor_data dataframe. Do you know why sdmTMB_simulate() might not be recognizing it?

**Comment by ericward-noaa** [comment]
Hmm, the above works for me -- with the 0 for intercept, it becomes

`sim_dat <- sdmTMB_simulate(
  formula = ~ hour_effect + log_depth + log_depth2,
  data = predictor_dat,
  time = "year",
  mesh = mesh,
  family = gaussian(),
  range = 0.5,
  sigma_E = 0.1,
  phi = 0.1,
  sigma_O = 0.2,
  seed = 42,
  B = c(0.2, -0.4, 0.02) # hour effect, linear depth, quadratic depth
)`

**Comment by jindivero** [comment]
Ah I was missing the tilda before the 0 in the formula line!

**Comment by jindivero** [comment]
Here are some updates on this:
1) I put together a basic vignette with visreg, but didn't add too much elaboration or add many other features because it seemed like everyone thought ggeffects would be the way to go anyway. But, here is that file:
https://github.com/pbs-assess/sdmTMB/blob/f6a94d59fea548505e2ed50951de253e70d2e985/julia-vignettes/visualization_with_visreg.Rmd

2) Here is the start of the vignette for using ggeffects: 
https://github.com/pbs-assess/sdmTMB/blob/f6a94d59fea548505e2ed50951de253e70d2e985/julia-vignettes/visualization_with_ggeffects.Rmd

Few things I wanted to note/ask: 
--Only ggeffect(), not ggpredict(), are working for me. Is there something different I should be doing with ggpredict() to get it to work? Or is ggeffect() the more useful function over ggpredict() anyway?
--Using the Pacific cod density data is not working for me (only presence data is), and I get an error about "not being able to find mu.eta" when I run the fit output in ggeffect().
--Is there a way to pull out the spatial and spatio-temporal terms from the sdmTMB model fit to plot those effects?
--For the simulated data example, I can run the sim_data() code you sent, but am getting errors when trying to fit the model with sdmTMB because the sim_dat produces a bunch of negative values in the observations. Do you have a suggestion for what model settings to use for that simulated data example?

Thank you!

(Also just fyi I was going to do these updates as pull requests, instead of commented here, because I thought it'd be easier, but I cannot find the "submit pull request" option when viewing the files on my branch, or when trying to do it through the "pull request" tab at the top of repository. I'll keep trying to figure that out!)

**Comment by seananderson** [comment]
> --Only ggeffect(), not ggpredict(), are working for me. Is there something different I should be doing with ggpredict() to get it to work? Or is ggeffect() the more useful function over ggpredict() anyway?

I haven't set it up to work with ggpredict yet.

> --Using the Pacific cod density data is not working for me (only presence data is), and I get an error about "not being able to find mu.eta" when I run the fit output in ggeffect().

Ah, you're right. The Tweedie family (and other custom families) were missing some standard family elements. I just fixed Tweedie on the 'dev' branch.

> --Is there a way to pull out the spatial and spatio-temporal terms from the sdmTMB model fit to plot those effects?

Not using visreg/ggeffects, but fairly easy to plot as in `?predict.sdmTMB` or the index vignette with ggplot. Eric was working on a generic package for this at one point.

> --For the simulated data example, I can run the sim_data() code you sent, but am getting errors when trying to fit the model with sdmTMB because the sim_dat produces a bunch of negative values in the observations. Do you have a suggestion for what model settings to use for that simulated data example?

Are you using a matching family (`gaussian()`?) in the fitting as in simulating?

Commenting here is fine. I can help with the pull request later.

**Comment by jindivero** [comment]
Thanks, Sean! ggeffect with the density data is working now, and I got the fit on the simulated data to work too.

**Comment by jindivero** [comment]
And thanks for pointing out that about visreg! I can add a brief note in the vignette about that.

**Comment by ecophilina** [comment]
Maybe note also that the middle option doesn't work for delta models. Or maybe take it out and suggest that it's safer to not use as.factor in the formula if one wants to use visreg.

**Comment by ericward-noaa** [comment]
Julia -- the package I'd started to build to do spatial diagnostics is here:
https://github.com/ericward-noaa/vista

I should probably move it to the spatial indicators repo or some other organization...

**Comment by jindivero** [comment]
I updated the visreg vignette with the note about as.factor: https://github.com/pbs-assess/sdmTMB/blob/2b2b8ad2edb6a1899703e806065b929b152d5b0e/julia-vignettes/visualization_with_visreg.Rmd

Let me know if you have any other comments/edits

**Comment by seananderson** [comment]
I just edited both vignettes. And, in looking at those vignettes I realized how amazing ggeffects is. So, I got ggpredict working too (locally), which does what visreg does but with fewer weird arguments and standard clean ggplot output as the default. It will require a tweak to ggeffects because if a model doesn't match an included class it defaults to a generic internal predict function that does not make use of the standard errors.

Perhaps we can scrap visreg support. Although we've already gone through all the pain of making it work...

**Comment by ericward-noaa** [comment]
I guess I'd vote to leave visreg there if folks want to use it, but not maintain it for future changes to visreg?

**Comment by seananderson** [comment]
visreg has been around for ages, so I'd guess it's not going to change quickly. visreg does seem to handle the partial randomized quantile residuals in link space nicely. For regular predictions in response space, ggeffect or ggpredict seems slicker.
