### ISSUE TITLE
Update delta-model vignette to use new built-in delta functionality

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#87]
Might as well still keep the illustration of fitting them independently as well.

Include showing how to use `simulate()`, `residuals()`, `predict()`, `tidy()`, etc. while picking a model or using both together.

**Comment by jindivero** [comment]
Just started on this: https://github.com/pbs-assess/sdmTMB/blob/d01e71c7197c04f5ece8ddbee7931a15e2eb7be4/julia-vignettes/delta_models.Rmd

**Comment by jindivero** [comment]
Hi! Here is a first draft of the vignette: https://github.com/pbs-assess/sdmTMB/blob/c2d234bb95accaa66c46d50b2a27169d1dd82e5c/julia-vignettes/delta_models.Rmd

Couple things I wanted to ask:
-I could use some help on using simulate() with the built-in delta functions. How does the simulate() function need parameters for each model component specified? I haven't gotten it to work yet.
-Will ggeffects work with built-in delta models yet? I got it working with visreg.
-I was wondering how someone could specify a different equation for each model component (e.g. including depth in only the density model, not presence-absence)? I wanted to include that but wasn't sure how to do it.
-Are there other specifications of the built-in models that you want us to show that I don't have in the vignette?

**Comment by seananderson** [comment]
Awesome, I just pushed some edits on the first half.

Some quick answers:

> Couple things I wanted to ask:
> -I could use some help on using simulate() with the built-in delta functions. How does the simulate() function need parameters for each model component specified? I haven't gotten it to work yet.

`simulate()` should work (simulating new observations from an existing fit), but I haven't set up `sdmTMB_simulate()` for it yet. You'd have to do it yourself (simulate the binomial, simulate Gamma, multiply it).

With simulate, see the `model` argument.

> -Will ggeffects work with built-in delta models yet? I got it working with visreg.

Probably won't work without some tweaks to the ggeffects fork.

> -I was wondering how someone could specify a different equation for each model component (e.g. including depth in only the density model, not presence-absence)? I wanted to include that but wasn't sure how to do it.

The same `list()` syntax with the caveat that there can't (yet) be different smoothers or different breakpoint effects or different IID random intercepts. e.g. `list(y ~ x + z, y ~ x2)`.

Details here: https://github.com/pbs-assess/sdmTMB/blob/921d3bee616aff296f156e38905a11fe45d385e2/R/fit.R#L241-L256

> -Are there other specifications of the built-in models that you want us to show that I don't have in the vignette?

Maybe describing the new columns in the prediction dataframe in a delta model?

Also how the printed model output looks.

And maybe how the anisotropy is shared across the 2 by default (as in VAST, and as of a recent 'dev' branch commit), but it can be made unique across the 2 components with:

`control = sdmTMBcontrol(map = list(ln_H_input = factor(c(1, 2, 3, 4))))`

`delta_poisson_link_gamma()` is a work in progress I've disabled in the latest dev branch commits until I test it more.

Using `tidy()` for either component.

The `model` arg in `predict.sdmTMB().

With residuals, see the `model` argument.

**Comment by jindivero** [comment]
Thanks, Sean! Just pushed a version with edits/additions for all of those points. Let me know if there's any parts you'd like me to add more details/examples/etc on.

The only thing I didn't address was using sdmTMB_simulate() to manually work for delta models. I decided to leave that out for now because it already seemed like a pretty long vignette. But I can add a section about that if you'd want me to! Or, I was wondering if simulating data with sdmTMB_simulate() was something you'd want an entirely separate vignette about.
