### ISSUE TITLE
Make predict work with newdata not expanded by time

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#92]
In cases where newdata is the same for all time slices and is large, it would save memory and speed (faster MakeADFun call) if newdata didn't have to be expanded to all time slices.

This is in progress in the 'shortnewdata' branch. Most of it is done, but not the random field mesh projections, which will take some more thought.

**Comment by ericward-noaa** [comment]
Sort of related, it would also be helpful to add an error message to `predict()` when `re_form_iid` is not specified -- but there are new levels in `newdata`. Without the error catching, this currently just blows up RStudio

`sub = dplyr::filter(pcod, year!=2017)
sub$fyear = as.factor(sub$year)

mesh <- make_mesh(sub, c("X", "Y"), cutoff = 20)

fit <- sdmTMB(density ~ s(depth),
              data = sub,
              mesh = mesh,
              family = tweedie(link = "log"),
              time = "year",
              spatial = "on",
              spatiotemporal = "iid",
              extra_time = 2017L,
              silent=FALSE)

pcod$fyear = as.factor(pcod$year)
pred = predict(fit, newdata=pcod, re_form_iid = NA) # works
pred = predict(fit, newdata=pcod) # blows up

`
