### ISSUE TITLE
Add Jacobian transformations for priors

### ISSUE THREAD

**Issue by seananderson** [pbs-assess/sdmTMB#95]
This will require an argument flag in `sdmTMB()` since they should only be applied if going to tmbstan, not for marginal maximum likelihood.

Regarding the PC prior, from @joenomiddlename:

> Regarding the PC prior sampling in Stan. I think the Jacobian is given in the Appendix (A.6 Theorem 2.6) of the preprint of the main text https://arxiv.org/pdf/1503.00256.pdf. The authors give the prior pdf in terms of the range / SD and the kappa / tau parametrizations. Then, I believe the (range) prior should only be used it once if the range is shared.
>
> It appears the paper breaks down the priors into the two parts, the range and the sd (lambda1 and lambda 2). The first part is marginal, the latter conditional

See screenshots below. And, it looks like I already set it up with the range and SD conditional on range priors separately inside the function, so it's just a matter of somehow only applying the range part once if the range is shared (I'll start a separate issue):

```
  Type range_ll = log(dhalf) + log(lam1) + log(pow(range, -1. - dhalf)) -
                  lam1 * pow(range, -dhalf);
  Type sigma_ll = log(lam2) - lam2 * sigma;
  Type penalty = range_ll + sigma_ll;
```

(in `src/utils.h`)

The transformation relevant to the Jacobian is just from the part inside the absolute value bars below. The log absolute derivative of the transform, so log(abs(D(transformation))). Then remember whether to add or subtract.

<img width="993" alt="Screenshot of Skim (2022-04-21, 11-02-54 PM)" src="https://user-images.githubusercontent.com/19349/170129278-a8f991e2-e4e8-40da-ab35-606c1614d7e2.png">

<img width="1154" alt="Screenshot of Skim (2022-04-21, 11-04-05 PM)" src="https://user-images.githubusercontent.com/19349/170129289-425a36bd-babb-4021-846d-c855d8617e8d.png">

<img width="1100" alt="Note that conditioning is equivalent to conditioning" src="https://user-images.githubusercontent.com/19349/170129300-ff578d6b-96e2-416c-9254-153a9e547f30.png">

**Comment by ericward-noaa** [comment]
Just making notes to myself. The Jacobian adjustments are just at the end of the lines on the marginals. They are:

P(sigma) = sqrt(8*nu) / (rho^2)

P(sigma | rho) = C * kappa^nu

And C is defined on P 18 of the PDF linked above, 
![image](https://user-images.githubusercontent.com/5046884/170500310-045cfb70-2858-4874-9ae9-15c8ba7ac551.png)
