### ISSUE TITLE
Visreg error

### ISSUE THREAD

**Issue by gfmg** [pbs-assess/sdmTMB#99]
Hi, 

I am running an sdmTMB model with the following structure.

```
 dat[[n]]<-subset(dat[[n]],Year >= 2012)
    dat[[n]]$fvessel<-factor(dat[[n]]$fvessel)
    dat[[n]]$Year<-as.factor(dat[[n]]$Year)
    dat[[n]]$Sediment<-as.factor(dat[[n]]$Sediment)
    
    pSCE_spde <- make_mesh(dat[[n]], c("XKm", "YKm"), cutoff = cutoof)
    
    res[[n]] <- sdmTMB(
      data = dat[[n]], 
      formula = LPUE ~ 0 + 
        Year + 
        Sediment +
        s(Month) +
        s(Depth) +
        s(significant_wave_height) +
        s(bottom_temperature) +
        s(BSdb) +
        (1 | fvessel),
      time = "Year", 
      spatial = "on",
      spatiotemporal = "IID",
      mesh = pSCE_spde, 
      family = Gamma(link = "log"))
``` 

I saw on the updated vignette that sdmTMB moved toward using `visreg` for plotting non-linear effects.  I went to test it out, with the fit above, but an Error is returned as follows (for any of the smooth effects): 

```
visreg::visreg(res[[1]],xvar = "bottom_temperature")
Error in exists(as.character(CALL$data), call.env) : 
  first argument has length > 1
```

I have checked this issue on visreg github and found the two following threads related to the subsetting of data within the model call function, but this is not the case in my example?

https://github.com/pbreheny/visreg/issues/98
https://github.com/pbreheny/visreg/issues/99

Many thanks and apologies if I am missing something obvious

G

**Comment by ericward-noaa** [comment]
Yes -- we're working on using `visreg` or `ggeffects` for visualizing the smooths. There's some examples in this vignette update (very much in development, but works): 
https://github.com/pbs-assess/sdmTMB/tree/julia-vignettes/julia-vignettes

I've tested Julia's examples with/without random effects, changing the family to Gamma (per your example), etc. and all work (visreg 2.7.0)

Can you maybe try testing these simple examples from the vignettes? If that doesn't work I can play with a subset of your data if you can send it to me.

**Comment by gfmg** [comment]
Hi, 

Indeed, it does seem as if visreg do not like the dat[[]] to be a list, or the subsetting done before applying the model.  When subsetting the dat[[]] list to a new data.frame object and applying the model, the visreg function works fine....

Many thanks for both of your answers 

G
